name: Conventional Commit Checker

on:
  push:
    branches: [ develop ]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Check commit message
        run: npx commitlint --from=${{ github.event.before }} --to=${{ github.event.after }}
