name: Conventional Commit Checker
on:
  push:
    branches:
      - develop

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if commit is conventional
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if ! echo "$commit_message" | grep -qE '^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([A-Za-z0-9-]+\))?: [^\n]{1,72}(?:\n\n[A-Za-z0-9\W]{1,})?$'; then
            echo "Commit message is not conventional"
            exit 1
          fi
